export const sample_foods = [
  {
    id: '1',
    name: 'Bánh Mì - Vietnamese Baguette',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Southern', 'Central', 'Northern'],
    stars: 4.5,
    imageUrl: 'Banh_Mi.png',
    tags: ['Starters'],
  },
  {
    id: '2',
    name: 'Phở Bò - Beef Noodle Soup',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Northern'],
    stars: 5,
    imageUrl: 'Pho_Bo.png',
    tags: ['NoodleSoups'],
  },
  {
    id: '3',
    name: 'Phở Gà - Chicken Noodle Soup',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Northern'],
    stars: 3.5,
    imageUrl: 'Pho_Ga.png',
    tags: ['NoodleSoups'],
  },
  {
    id: '4',
    name: 'Gỏi Cuốn - Fresh Saigon Roll',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Southern', 'Central'],
    stars: 3,
    imageUrl: 'Goi_Cuon.png',
    tags: ['Starters'],
  },
  {
    id: '5',
    name: 'Cơm Tấm Sườn Heo - Pork Ribs Broken Rice',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Southern'],
    stars: 3.5,
    imageUrl: 'Com_Tam.png',
    tags: ['Rice'],
  },
  {
    id: '6',
    name: 'Cà Phê Trứng - Vietnamese Egg Coffee',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Northern'],
    stars: 4.0,
    imageUrl: 'Cafe_Trung.png',
    tags: ['Drinks'],
  },
  {
    id: '7',
    name: 'Cà Phê Sữa Đá - Vietnamese Drip Coffee',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Northern', 'Southern', 'Central'],
    stars: 4.0,
    imageUrl: 'Cafe_Sua_Da.png',
    tags: ['Drinks'],
  },
  {
    id: '8',
    name: 'Bún Bò Huế - Spicy Noodle Soup',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Central'],
    stars: 4.0,
    imageUrl: 'Bun_Bo_Hue.png',
    tags: ['NoodleSoups'],
  },
  {
    id: '9',
    name: 'Bánh Bột Lọc - Shrimp Tapioca Dumblings',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Central'],
    stars: 4.0,
    imageUrl: 'Banh_Bot_Loc.png',
    tags: ['Starters'],
  },
  {
    id: '10',
    name: 'Bánh Bèo Chén - Steamed Rice Shrimp Cakes',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Central'],
    stars: 4.0,
    imageUrl: 'Banh_Beo_Chen.png',
    tags: ['Starters'],
  },
];

export const sample_tags = [
  { name: 'All', count: 10 },
  { name: 'Starters', count: 4 },
  { name: 'Drinks', count: 2 },
  { name: 'NoodleSoups', count: 3 },
  { name: 'Rice', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false,
  },
];